@BASE_URL=http://192.168.10.21:9009
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsInNjb3BlIjoiZGVmYXVsdCIsImZvcmNlQ2hhbmdlUGFzc3dvcmQiOmZhbHNlLCJleHAiOjE2NTgxNTY3MTgsImlhdCI6MTY1ODEyNzkxOH0.2pZ2_w5_z4My9JF_S1sY7J7jRDF2ijWFjxyJAwJ58Gc
@API_KEY=ptr_oWGwCd90hxZqm/5U7uK5jTANypVW99lpxloa9jAmCHk=
@ENVIRONMENT=1
@CONTAINER_ID=b9aa4d35f530e2c087831f1e99605c4ae1ef266ce4c56676a5ca99de8fe7071e

GET https://example.com HTTP/1.1

###

POST {{BASE_URL}}/api/auth  HTTP/1.1
content-type: application/json

{
  "Username": "admin",
  "Password": "Aa1234567890"
}

###

# create container
# https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate
# https://docs.portainer.io/v/ce-2.9/api/examples#create-a-container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/create?name=web01
Authorization: Bearer {{JWT}}
X-API-Key: {{API_KEY}}
content-type: application/json

{
  "Image":"traefik/whoami:latest",
  "ExposedPorts":{ "80/tcp":{} },
  "HostConfig":{ "PortBindings":{ "80/tcp":[{ "HostPort": "8080" }] } }
}

###
GET {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/json HTTP/1.1
Authorization: Bearer {{JWT}}
X-API-Key: {{API_KEY}}

###

# Start a container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}}/start
Authorization: Bearer {{JWT}}

{}

###

# stop a container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}}/stop
Authorization: Bearer {{JWT}}

{}

###

# delete container
DELETE {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}} 
Authorization: Bearer {{JWT}}

{"force": true}

###
