@BASE_URL=http://192.168.10.21:9009
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsInNjb3BlIjoiZGVmYXVsdCIsImZvcmNlQ2hhbmdlUGFzc3dvcmQiOmZhbHNlLCJleHAiOjE2NTgxNTY0MjMsImlhdCI6MTY1ODEyNzYyM30.pS1jChPFlVnSmZze0PP2z3XqWuupxGo433N16mish8Y
@API_KEY=ptr_oWGwCd90hxZqm/5U7uK5jTANypVW99lpxloa9jAmCHk=
@ENVIRONMENT=1
@CONTAINER_ID=4cf2e38552d5f6595cb01ad8949f7bff9a987354fa316aef1bf995dd0d836146

GET https://example.com HTTP/1.1

###

GET {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/json HTTP/1.1
Authorization: Bearer {{JWT}}
X-API-Key: {{API_KEY}}
###

# Start a container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}}/start
Authorization: Bearer {{JWT}}

{}

###

# stop a container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}}/stop
Authorization: Bearer {{JWT}}

{}

###

# delete container
DELETE {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/{{CONTAINER_ID}} 
Authorization: Bearer {{JWT}}

{"force": true}

###

# create container
# https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate
# https://docs.portainer.io/v/ce-2.9/api/examples#create-a-container
POST {{BASE_URL}}/api/endpoints/{{ENVIRONMENT}}/docker/containers/create?name=web01
Authorization: Bearer {{JWT}}
X-API-Key: {{API_KEY}}
content-type: application/json

{
  "Image":"nginx:latest",
  "ExposedPorts":{ "80/tcp":{} },
  "HostConfig":{ "PortBindings":{ "80/tcp":[{ "HostPort": "8080" }] } }
}

###
POST {{BASE_URL}}/api/auth  HTTP/1.1
content-type: application/json

{
  "Username": "admin",
  "Password": "Aa1234567890"
}
