version: '3.9'
services:
  web:
    build: .
    user: '1000'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    mem_limit: 2000m
    command: sleep infinity

  redis:
    image: redis
    # container_name: node_challenge_redis
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: --port 6380
    ports:
      - '6380:6380'
    expose:
      - '6380'
