version: '3.9'
services:
  # web:
  #   build: .
  #   user: '1000'
  #   volumes:
  #     - .:/src
  #   ports:
  #     - '8000:5000'
  #   mem_limit: 2000m

  redis:
    image: redis
    # container_name: node_challenge_redis
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: --port 6380
    ports:
      - '6380:6380'
    expose:
      - '6380'

  # environments -> add environment -> docker -> start wizard -> agent -> host=agent-test:9001 -> environment URL=agent-test:9001 -> finish
  # agent-test:9001
  portainer-agent-test:
    container_name: agent-test
    image: portainer/agent
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-ce-test:
    container_name: portainer-ce-test
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Asia/Hong_Kong'
      VERSION: 'docker'
    volumes:
      # - './volumes/portainer_data/:/data'
      # - './volumes/:/app/data/custom/'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./pass:/tmp/pass
    ports:
      #- 8000:8000  # only required if using the Edge compute features with Edge agents
      - 9009:9000 # http
      # - 9443:9443 # https
    command: --admin-password-file /tmp/pass
    # command: --admin-password '${CONFIG_PORTAINER_ADMIN_PW}'
